=== VinniZP/the-ants-helpers/docs/building-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Building Schema",
  "description": "Schema for building data structure",
  "definitions": {
    "BuildingId": {
      "type": "string",
      "enum": [
        "queen",
        "worker_ant_nest",
        "woodlouse_colony",
        "wet_soil_pile",
        "wet_soil_depot",
        "wet_soil_depot_2",
        "wet_soil_depot_3",
        "trophy_storeroom",
        "troop_tunnel",
        "treasure_depot",
        "toxic_fungi",
        "termite_farm",
        "supreme_native_fungi",
        "spring",
        "special_nest",
        "special_ant_habitat",
        "soldiers_reform_pool",
        "shooter_ant_nest",
        "sentinel_tree",
        "sand_pile",
        "sand_depot",
        "sand_depot_2",
        "sand_depot_3",
        "resource_tunnel",
        "resource_factory",
        "reservoir",
        "reservoir_2",
        "reservoir_3",
        "rally_center_i",
        "rally_center_ii",
        "rally_center_iii",
        "pro_rally_center",
        "plant_flora",
        "plant_depot",
        "plant_depot_2",
        "plant_depot_3",
        "native_fungi",
        "mutation_pool",
        "mutation_flora",
        "meat_depot",
        "meat_depot_2",
        "meat_depot_3",
        "leafcutter",
        "ladybug_habitat",
        "insect_nest",
        "insect_habitat",
        "healing_pool",
        "guardian_ant_nest",
        "fungus_depot",
        "fungus_depot_2",
        "fungus_depot_3",
        "feeding_ground",
        "evolution_fungi",
        "entrance",
        "construction_center",
        "cocoon_medium",
        "carrier_ant_nest",
        "aphid",
        "alliance_center"
      ]
    },
    "BuildingLevel": {
      "type": "object",
      "properties": {
        "depotCapacity": {
          "type": "number",
          "minimum": 0
        },
        "level": {
          "type": "number",
          "minimum": 1
        },
        "meat": {
          "type": "number",
          "minimum": 0
        },
        "fungus": {
          "type": "number",
          "minimum": 0
        },
        "plant": {
          "type": "number",
          "minimum": 0
        },
        "wet_soil": {
          "type": "number",
          "minimum": 0
        },
        "sand": {
          "type": "number",
          "minimum": 0
        },
        "diamonds": {
          "type": "number",
          "minimum": 0
        },
        "power": {
          "type": "number"
        },
        "power_delta": {
          "type": "number"
        },
        "population": {
          "type": "number",
          "minimum": 0
        },
        "honeydew": {
          "type": "number",
          "minimum": 0
        },
        "time": {
          "type": "number",
          "minimum": 0
        },
        "notes": {
          "type": "string"
        },
        "requirements": {
          "type": "object",
          "additionalProperties": {
            "type": "number",
            "minimum": 0
          },
          "patternProperties": {
            "^(queen|worker_ant_nest|woodlouse_colony|wet_soil_pile|wet_soil_depot|wet_soil_depot_2|wet_soil_depot_3|trophy_storeroom|troop_tunnel|treasure_depot|toxic_fungi|termite_farm|supreme_native_fungi|spring|special_nest|special_ant_habitat|soldiers_reform_pool|shooter_ant_nest|sentinel_tree|sand_pile|sand_depot|sand_depot_2|sand_depot_3|resource_tunnel|resource_factory|reservoir|reservoir_2|reservoir_3|rally_center_i|rally_center_ii|rally_center_iii|pro_rally_center|plant_flora|plant_depot|plant_depot_2|plant_depot_3|native_fungi|mutation_pool|mutation_flora|meat_depot|meat_depot_2|meat_depot_3|leafcutter|ladybug_habitat|insect_nest|insect_habitat|healing_pool|guardian_ant_nest|fungus_depot|fungus_depot_2|fungus_depot_3|feeding_ground|evolution_fungi|entrance|construction_center|cocoon_medium|carrier_ant_nest|aphid|alliance_center)$": {
              "type": "number",
              "minimum": 0
            }
          }
        }
      },
      "required": [
        "level",
        "meat",
        "fungus",
        "plant",
        "wet_soil",
        "sand",
        "diamonds",
        "power",
        "power_delta",
        "population",
        "honeydew",
        "time",
        "notes",
        "requirements"
      ],
      "additionalProperties": false
    },
    "Building": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/definitions/BuildingId"
        },
        "depotType": {
          "type": "string",
          "enum": ["meat", "fungus", "plant", "wet_soil", "sand", "water"]
        },
        "levels": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/BuildingLevel"
          },
          "minItems": 1
        },
        "warns": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["id", "levels", "warns"],
      "additionalProperties": false
    }
  },
  "type": "object",
  "$ref": "#/definitions/Building"
}

=== VinniZP/the-ants-helpers/docs/buildings/wet_soil_depot_3.json
{
  "$schema": "../building-schema.json",
  "id": "wet_soil_depot_3",
  "depotType": "wet_soil",
  "levels": [
    {
      "depotCapacity": 20000000,
      "level": 1,
      "meat": 0,
      "fungus": 0,
      "plant": 16000000,
      "wet_soil": 0,
      "sand": 3200000,
      "diamonds": 0,
      "power": 1480,
      "power_delta": 1480,
      "population": 0,
      "honeydew": 0,
      "time": 0,
      "notes": "",
      "requirements": {
        "queen": 20,
        "wet_soil_depot_2": 10
      }
    },
    {
      "depotCapacity": 40000000,
      "level": 2,
      "meat": 0,
      "fungus": 0,
      "plant": 26000000,
      "wet_soil": 0,
      "sand": 5200000,
      "diamonds": 8746,
      "power": 2038,
      "power_delta": 558,
      "population": 0,
      "honeydew": 6800000,
      "time": 5495.166666666667,
      "notes": "",
      "requirements": {
        "queen": 20,
        "wet_soil_depot_2": 10
      }
    },
    {
      "depotCapacity": 60000000,
      "level": 3,
      "meat": 0,
      "fungus": 0,
      "plant": 42000000,
      "wet_soil": 0,
      "sand": 8400000,
      "diamonds": 11075,
      "power": 2662,
      "power_delta": 624,
      "population": 0,
      "honeydew": 8800000,
      "time": 7143.833333333333,
      "notes": "",
      "requirements": {
        "queen": 20,
        "wet_soil_depot_2": 10
      }
    },
    {
      "depotCapacity": 80000000,
      "level": 4,
      "meat": 0,
      "fungus": 0,
      "plant": 64000000,
      "wet_soil": 0,
      "sand": 12000000,
      "diamonds": 14023,
      "power": 3460,
      "power_delta": 798,
      "population": 0,
      "honeydew": 10000000,
      "time": 9286.833333333334,
      "notes": "",
      "requirements": {
        "queen": 20,
        "wet_soil_depot_2": 10
      }
    },
    {
      "depotCapacity": 100000000,
      "level": 5,
      "meat": 0,
      "fungus": 0,
      "plant": 86000000,
      "wet_soil": 0,
      "sand": 16000000,
      "diamonds": 17758,
      "power": 4578,
      "power_delta": 1118,
      "population": 0,
      "honeydew": 12000000,
      "time": 12073,
      "notes": "",
      "requirements": {
        "queen": 20,
        "wet_soil_depot_2": 10
      }
    },
    {
      "depotCapacity": 120000000,
      "level": 6,
      "meat": 0,
      "fungus": 0,
      "plant": 100000000,
      "wet_soil": 0,
      "sand": 22000000,
      "diamonds": 24037,
      "power": 6387,
      "power_delta": 1809,
      "population": 0,
      "honeydew": 16000000,
      "time": 16902.166666666668,
      "notes": "",
      "requirements": {
        "queen": 20,
        "wet_soil_depot_2": 10
      }
    },
    {
      "depotCapacity": 140000000,
      "level": 7,
      "meat": 0,
      "fungus": 0,
      "plant": 201600000000,
      "wet_soil": 0,
      "sand": 26000000,
      "diamonds": 32536,
      "power": 8942,
      "power_delta": 2555,
      "population": 0,
      "honeydew": 18000000,
      "time": 23662.833333333332,
      "notes": "",
      "requirements": {
        "queen": 20,
        "wet_soil_depot_2": 10
      }
    },
    {
      "depotCapacity": 160000000,
      "level": 8,
      "meat": 0,
      "fungus": 0,
      "plant": 230400000000,
      "wet_soil": 0,
      "sand": 32000000,
      "diamonds": 44042,
      "power": 12514,
      "power_delta": 3572,
      "population": 0,
      "honeydew": 20000000,
      "time": 33128,
      "notes": "",
      "requirements": {
        "queen": 20,
        "wet_soil_depot_2": 10
      }
    },
    {
      "depotCapacity": 180000000,
      "level": 9,
      "meat": 0,
      "fungus": 0,
      "plant": 160000000,
      "wet_soil": 0,
      "sand": 34000000,
      "diamonds": 59615,
      "power": 17255,
      "power_delta": 4741,
      "population": 0,
      "honeydew": 24000000,
      "time": 46379.166666666664,
      "notes": "",
      "requirements": {
        "queen": 20,
        "wet_soil_depot_2": 10
      }
    },
    {
      "depotCapacity": 200000000,
      "level": 10,
      "meat": 0,
      "fungus": 0,
      "plant": 180000000,
      "wet_soil": 0,
      "sand": 36000000,
      "diamonds": 80696,
      "power": 24495,
      "power_delta": 7240,
      "population": 0,
      "honeydew": 26000000,
      "time": 64930.833333333336,
      "notes": "",
      "requirements": {
        "queen": 20,
        "wet_soil_depot_2": 10
      }
    }
  ],
  "warns": []
}

=== VinniZP/the-ants-helpers/docs/buildings copy/wet_soil_depot_2.json
{
  "$schema": "../building-schema.json",
  "id": "wet_soil_depot_2",
  "depotType": "wet_soil",
  "levels": [
    {
      "depotCapacity": 2000000,
      "level": 1,
      "meat": 0,
      "fungus": 0,
      "plant": 420000,
      "wet_soil": 0,
      "sand": 84000,
      "diamonds": 0,
      "power": 161.0,
      "power_delta": 161.0,
      "population": 0,
      "honeydew": 0,
      "time": 0.0,
      "notes": "",
      "requirements": {
        "queen": 13,
        "wet_soil_depot": 10
      }
    },
    {
      "depotCapacity": 4000000,
      "level": 2,
      "meat": 0,
      "fungus": 0,
      "plant": 660000,
      "wet_soil": 0,
      "sand": 120000,
      "diamonds": 1123,
      "power": 210.0,
      "power_delta": 49.0,
      "population": 0,
      "honeydew": 320000,
      "time": 561.5,
      "notes": "",
      "requirements": {
        "queen": 13,
        "wet_soil_depot": 10
      }
    },
    {
      "depotCapacity": 6000000,
      "level": 3,
      "meat": 0,
      "fungus": 0,
      "plant": 1000000,
      "wet_soil": 0,
      "sand": 200000,
      "diamonds": 1422,
      "power": 276.0,
      "power_delta": 66.0,
      "population": 0,
      "honeydew": 440000,
      "time": 729.8333333333334,
      "notes": "",
      "requirements": {
        "queen": 13,
        "wet_soil_depot": 10
      }
    },
    {
      "depotCapacity": 8000000,
      "level": 4,
      "meat": 0,
      "fungus": 0,
      "plant": 1800000,
      "wet_soil": 0,
      "sand": 380000,
      "diamonds": 1925,
      "power": 389.0,
      "power_delta": 113.0,
      "population": 0,
      "honeydew": 600000,
      "time": 1021.8333333333334,
      "notes": "",
      "requirements": {
        "queen": 13,
        "wet_soil_depot": 10
      }
    },
    {
      "depotCapacity": 10000000,
      "level": 5,
      "meat": 0,
      "fungus": 0,
      "plant": 3400000,
      "wet_soil": 0,
      "sand": 660000,
      "diamonds": 2605,
      "power": 532.0,
      "power_delta": 143.0,
      "population": 0,
      "honeydew": 840000,
      "time": 1430.5,
      "notes": "",
      "requirements": {
        "queen": 13,
        "wet_soil_depot": 10
      }
    },
    {
      "depotCapacity": 15000000,
      "level": 6,
      "meat": 0,
      "fungus": 0,
      "plant": 5800000,
      "wet_soil": 0,
      "sand": 1200000,
      "diamonds": 3527,
      "power": 746.0,
      "power_delta": 214.0,
      "population": 0,
      "honeydew": 1400000,
      "time": 2002.6666666666667,
      "notes": "",
      "requirements": {
        "queen": 13,
        "wet_soil_depot": 10
      }
    },
    {
      "depotCapacity": 25000000,
      "level": 7,
      "meat": 0,
      "fungus": 0,
      "plant": 10000000,
      "wet_soil": 0,
      "sand": 2000000,
      "diamonds": 4773,
      "power": 1063.0,
      "power_delta": 317.0,
      "population": 0,
      "honeydew": 2400000,
      "time": 2803.6666666666665,
      "notes": "",
      "requirements": {
        "queen": 13,
        "wet_soil_depot": 10
      }
    },
    {
      "depotCapacity": 35000000,
      "level": 8,
      "meat": 0,
      "fungus": 0,
      "plant": 18000000,
      "wet_soil": 0,
      "sand": 3600000,
      "diamonds": 6461,
      "power": 1488.0,
      "power_delta": 425.0,
      "population": 0,
      "honeydew": 4200000,
      "time": 3925.1666666666665,
      "notes": "",
      "requirements": {
        "queen": 13,
        "wet_soil_depot": 10
      }
    },
    {
      "depotCapacity": 45000000,
      "level": 9,
      "meat": 0,
      "fungus": 0,
      "plant": 30000000,
      "wet_soil": 0,
      "sand": 6200000,
      "diamonds": 8746,
      "power": 2037.0,
      "power_delta": 549.0,
      "population": 0,
      "honeydew": 6800000,
      "time": 5495.166666666667,
      "notes": "",
      "requirements": {
        "queen": 13,
        "wet_soil_depot": 10
      }
    },
    {
      "depotCapacity": 55000000,
      "level": 10,
      "meat": 0,
      "fungus": 0,
      "plant": 50000000,
      "wet_soil": 0,
      "sand": 9600000,
      "diamonds": 11075,
      "power": 2693.0,
      "power_delta": 656.0,
      "population": 0,
      "honeydew": 8800000,
      "time": 7143.833333333333,
      "notes": "",
      "requirements": {
        "queen": 13,
        "wet_soil_depot": 10
      }
    }
  ],
  "warns": []
}

=== VinniZP/the-ants-helpers/docs/buildings copy/wet_soil_depot.json
{
  "$schema": "../building-schema.json",
  "id": "wet_soil_depot",
  "depotType": "wet_soil",
  "levels": [
    {
      "depotCapacity": 0,
      "level": 0,
      "meat": 0,
      "fungus": 0,
      "plant": 0,
      "wet_soil": 0,
      "sand": 0,
      "diamonds": 0,
      "power": 0.0,
      "power_delta": 0.0,
      "population": 0,
      "honeydew": 420,
      "time": 0.0,
      "notes": "",
      "requirements": {
        "queen": 1
      }
    },
    {
      "depotCapacity": 30000,
      "level": 1,
      "meat": 0,
      "fungus": 0,
      "plant": 0,
      "wet_soil": 280,
      "sand": 0,
      "diamonds": 0,
      "power": 52.0,
      "power_delta": 52.0,
      "population": 0,
      "honeydew": 0,
      "time": 0.0,
      "notes": "",
      "requirements": {}
    },
    {
      "depotCapacity": 50000,
      "level": 2,
      "meat": 0,
      "fungus": 0,
      "plant": 0,
      "wet_soil": 1400,
      "sand": 6400,
      "diamonds": 19,
      "power": 54.0,
      "power_delta": 2.0,
      "population": 0,
      "honeydew": 3200,
      "time": 6.0,
      "notes": "",
      "requirements": {
        "wet_soil_pile": 2
      }
    },
    {
      "depotCapacity": 100000,
      "level": 3,
      "meat": 0,
      "fungus": 0,
      "plant": 0,
      "wet_soil": 2200,
      "sand": 9400,
      "diamonds": 25,
      "power": 56.0,
      "power_delta": 2.0,
      "population": 0,
      "honeydew": 4600,
      "time": 7.833333333333333,
      "notes": "",
      "requirements": {
        "wet_soil_pile": 3
      }
    },
    {
      "depotCapacity": 200000,
      "level": 4,
      "meat": 0,
      "fungus": 0,
      "plant": 0,
      "wet_soil": 3200,
      "sand": 14000,
      "diamonds": 35,
      "power": 59.0,
      "power_delta": 3.0,
      "population": 0,
      "honeydew": 7000,
      "time": 11.833333333333334,
      "notes": "",
      "requirements": {
        "wet_soil_pile": 4
      }
    },
    {
      "depotCapacity": 300000,
      "level": 5,
      "meat": 0,
      "fungus": 0,
      "plant": 0,
      "wet_soil": 4800,
      "sand": 22000,
      "diamonds": 50,
      "power": 64.0,
      "power_delta": 5.0,
      "population": 0,
      "honeydew": 10000,
      "time": 17.666666666666668,
      "notes": "",
      "requirements": {
        "wet_soil_pile": 5
      }
    },
    {
      "depotCapacity": 400000,
      "level": 6,
      "meat": 0,
      "fungus": 0,
      "plant": 0,
      "wet_soil": 6800,
      "sand": 30000,
      "diamonds": 93,
      "power": 86.0,
      "power_delta": 22.0,
      "population": 0,
      "honeydew": 16000,
      "time": 35.166666666666664,
      "notes": "",
      "requirements": {
        "wet_soil_pile": 6
      }
    },
    {
      "depotCapacity": 500000,
      "level": 7,
      "meat": 0,
      "fungus": 0,
      "plant": 0.0,
      "wet_soil": 9400,
      "sand": 42000,
      "diamonds": 174,
      "power": 120.0,
      "power_delta": 34.0,
      "population": 0,
      "honeydew": 26000,
      "time": 70.33333333333333,
      "notes": "",
      "requirements": {
        "wet_soil_pile": 7
      }
    },
    {
      "depotCapacity": 700000,
      "level": 8,
      "meat": 0,
      "fungus": 0,
      "plant": 0.0,
      "wet_soil": 12000,
      "sand": 60000,
      "diamonds": 323,
      "power": 168.0,
      "power_delta": 48.0,
      "population": 0,
      "honeydew": 42000,
      "time": 140.5,
      "notes": "",
      "requirements": {
        "wet_soil_pile": 8
      }
    },
    {
      "depotCapacity": 1000000,
      "level": 9,
      "meat": 0,
      "fungus": 0,
      "plant": 0,
      "wet_soil": 18000,
      "sand": 82000,
      "diamonds": 437,
      "power": 243.0,
      "power_delta": 75.0,
      "population": 0,
      "honeydew": 80000,
      "time": 196.66666666666666,
      "notes": "",
      "requirements": {
        "wet_soil_pile": 9
      }
    },
    {
      "depotCapacity": 2000000,
      "level": 10,
      "meat": 0,
      "fungus": 0,
      "plant": 0,
      "wet_soil": 26000,
      "sand": 120000,
      "diamonds": 554,
      "power": 338.0,
      "power_delta": 95.0,
      "population": 0,
      "honeydew": 94000,
      "time": 255.66666666666666,
      "notes": "",
      "requirements": {
        "wet_soil_pile": 10
      }
    }
  ],
  "warns": []
}
